CREATE ROLE UM_IB_MONITOR NOT IDENTIFIED;

-- Object privileges granted to UM_IB_MONITOR
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGARCHPC TO UM_IB_MONITOR;
GRANT SELECT ON <SCHEMA>.PSAPMSGARCHPD TO UM_IB_MONITOR;
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGARCHPH TO UM_IB_MONITOR;
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGARCHSC TO UM_IB_MONITOR;
GRANT SELECT ON <SCHEMA>.PSAPMSGDOMSTAT TO UM_IB_MONITOR;
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGPUBCON TO UM_IB_MONITOR;
GRANT SELECT ON <SCHEMA>.PSAPMSGPUBDATA TO UM_IB_MONITOR;
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGPUBHDR TO UM_IB_MONITOR;
GRANT SELECT, UPDATE ON <SCHEMA>.PSAPMSGSUBCON TO UM_IB_MONITOR;
GRANT DELETE, INSERT, SELECT, UPDATE ON <SCHEMA>.PSNODESDOWN TO UM_IB_MONITOR;
